require_relative './alphabet'

#This is a subclass of Alphabet class.
#It represents an english alphabet generated by duplicating letters twice from english alphabet.
class EchoAlphabet < Alphabet

  #This method is overridden to duplicate the english alphabet letters.
  def letters(number)
    super.zip(super).flatten
  end
end