require_relative './alphabet'

#This is a subclass of Alphabet class.
#It represents an english alphabet generated by duplicating letters twice from english alphabet.
class EchoFormat
  #This method is overridden to duplicate the english alphabet letters.
  def initialize(alphabet, number)
  	@alphabets = alphabet.letters(number)
  end

  def format
    @alphabets.zip(@alphabets).flatten.join('')
  end
end


echo_format = EchoFormat.new(Alphabet.new, 5)
puts echo_format.format
